In [1]:
import pandas as pd
import matplotlib.pyplot as pyp

/home/poojandoshi/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
df = pd.read_csv("weather.csv")

In [3]:
df.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy

In [4]:
col = df.columns

In [5]:
y = df['Weather Type'] 
y
df.drop(columns=['Weather Type'], inplace=True)
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain
...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain

In [6]:
object_columns = df.select_dtypes(include=['object']).columns.tolist()
df.drop(columns=object_columns, inplace=True)

In [7]:
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
0,14.0,73,9.5,82.0,1010.82,2,3.5
1,39.0,96,8.5,71.0,1011.43,7,10.0
2,30.0,64,7.0,16.0,1018.72,5,5.5
3,38.0,83,1.5,82.0,1026.25,7,1.0
4,27.0,74,17.0,66.0,990.67,1,2.5
...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,1003.15,1,1.0
13196,-1.0,76,3.5,23.0,1067.23,1,6.0
13197,30.0,77,5.5,28.0,1012.69,3,9.0
13198,3.0,76,10.0,94.0,984.27,0,2.0
13199,-5.0,38,0.0,92.0,1015.37,5,10.0

In [8]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the features
df_normalized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [9]:
df_normalized

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
0,0.291045,0.595506,0.195876,0.752294,0.527951,0.142857,0.175
1,0.477612,0.853933,0.175258,0.651376,0.529480,0.500000,0.500
2,0.410448,0.494382,0.144330,0.146789,0.547746,0.357143,0.275
3,0.470149,0.707865,0.030928,0.752294,0.566614,0.500000,0.050
4,0.388060,0.606742,0.350515,0.605505,0.477461,0.071429,0.125
...,...,...,...,...,...,...,...
13195,0.261194,0.606742,0.298969,0.651376,0.508732,0.071429,0.050
13196,0.179104,0.629213,0.072165,0.211009,0.669298,0.071429,0.300
13197,0.410448,0.640449,0.113402,0.256881,0.532637,0.214286,0.450
13198,0.208955,0.629213,0.206186,0.862385,0.461425,0.000000,0.100
13199,0.149254,0.202247,0.000000,0.844037,0.539352,0.357143,0.500

In [11]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.3, random_state=42)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Initialize the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Print classification report
report = classification_report(y_test, y_pred)
print('Classification Report:')
print(report)

Accuracy: 0.90
Classification Report:
              precision    recall  f1-score   support

      Cloudy       0.87      0.87      0.87       955
       Rainy       0.90      0.91      0.90       982
       Snowy       0.93      0.94      0.93      1033
       Sunny       0.91      0.89      0.90       990

    accuracy                           0.90      3960
   macro avg       0.90      0.90      0.90      3960
weighted avg       0.90      0.90      0.90      3960